### ISSUE TITLE
.

### ISSUE THREAD

**Issue by cferrari1** [TomerAberbach/spotify-true-random#1]
.

**Comment by Mehvix** [comment]
I'm having this issue too ("Play" function does not work when playlist contains Local Songs), I'm assuming this is an issue on Spotify's end? (I know you can't stream offline media to devices natively)

**Comment by TomerAberbach** [comment]
You can't use the Spotify API to play local songs, but maybe it's possible to play only the nonlocal songs from a playlist. I haven't worked on this in a while, and can't commit to looking into this issue at the moment, but I'd certainly accept a PR!
