### ISSUE TITLE
Certain playlists won't initiate 

### ISSUE THREAD

**Issue by WarKittens** [TomerAberbach/spotify-true-random#12]
When using True Random to play playlists, certain playlists will not initiate. I have made new playlists with the same contents, I have changed the titles, etc and it just will not start this playlist. Here are the URLs for the playlists. Your guess is as good as mine.
https://open.spotify.com/playlist/144jB6UnKAtII72igCnaOt?si=4PTBB--dRs2x5TuaVx4KFQ&pi=u-ST87ggLhTFKL

https://open.spotify.com/playlist/0h2DsBBC1SPCoqnvEerYr7?si=yA6P-MzuTuG6Rqzx8vfbvA&pi=u-UHW69rsXSfCj

https://open.spotify.com/playlist/5cYAHtI0do6diNda18I4rz?si=xy4hRaPjT6eDZ9pZyXKw9w&pi=u-WrqnfzWoTJ-v

Yet this playlist which includes everything on the playlists that won't start initiates just fine.

https://open.spotify.com/playlist/2GmIsrMu0e3PBO6WZ1OVba?si=t6B8N1y0QnOF7BNgl-VO9Q&pi=u-atb8LmuET1GJ

Let me know if you need any more info. This thing works great otherwise!

**Comment by TomerAberbach** [comment]
I think it's because the playlists have local tracks:
```
{
  "error" : {
    "status" : 400,
    "message" : "Invalid track uri: spotify:local:AudioLab::Jungkook+Seven+explicit+without+Latto_11-08-23_18-00-17-722:149"
  }
}
```

Unfortunately, I don't think the Spotify API supports playing local tracks, so not sure there's anything I could do on my end (beyond making the application show an error message about it or something)

**Comment by WarKittens** [comment]
Thank you for making me look twice! I swear I removed them all for the Why Are You Being Difficult playlist but I missed one! That was my first guess about what was causing the problem. Thanks for looking into it and confirming the issue. You are awesome! 🤙🏻

**Comment by TomerAberbach** [comment]
No problem :)
