### ISSUE TITLE
All playlists not showing 

### ISSUE THREAD

**Issue by WarKittens** [TomerAberbach/spotify-true-random#13]
Starting this morning 4/4/24, all of my playlists are not showing. I am signed in to the correct Spotify account and kartikk221's True Shuffle Github project is still showing all my playlists. I think you both use the same API.

I can't figure out what the criteria is for which playlists make the cut.

What info would you like from me about the playlists that show up?

**Comment by TomerAberbach** [comment]
Hmmm, not sure. I haven't changed anything recently and it works for me... Maybe try the usual suspects first and we can take it from there? (clearing cache, restarting your browser, etc.)

**Comment by TomerAberbach** [comment]
Feel free to reopen if this is still a problem
