### ISSUE TITLE
NEW ISSUE SINCE UPDATED LINK

### ISSUE THREAD

**Issue by GayLemonade** [TomerAberbach/spotify-true-random#15]
hi tomer aberbach, I'm back. I noticed an oversight that I didn't see before. 

so in any Spotify queue you can only see the first 50 songs in the "next from:" queue. with the old link though, I remember as the songs in the queue advanced new songs would add at the end of that list in some invisible off screen queue that consisted of every song on the playlist. that way where the queue would only actually end when every song has played one time exactly.

with the new link it seems to only queue 50 songs in the queue and when one song advances new ones aren't added to the end. making you either press play again to loop those same 50 songs in that order, or randomize a new set of 50 which would lead to songs being repeated. 

this issue is proving to be pretty inconvenient to me as a user so if you have time to figure out what may be causing this bug it would be greatly appreciated. thank you again for your time.

**Comment by GayLemonade** [comment]
also (I just tested a few times) it seems to only be shuffling the first maybe half of my playlist every time I randomize. it will absolutely not play a song from the lower half. i suspect it to be only shuffling the first 50 because the queue has the same songs in it every time. but I haven't tested enough to say for sure it's the first 50, just enough to say it's definitely just not seeing a large lower portion of my playlists

**Comment by TomerAberbach** [comment]
Good catch. Fixed in https://github.com/TomerAberbach/spotify-true-random/commit/2e64a675f1a60a6f67bc7e704a23a6bb0b6b4250
