### ISSUE TITLE
Nothing happens, just queueing forever

### ISSUE THREAD

**Issue by Number-313** [TomerAberbach/spotify-true-random#16]
Hello,
I'm not sure if this project is still alive, but I've tried it and nothing happens after clicking on "Play". It just says "Queueing" forever, then nothing happens.
I'm trying to play on a web browser with Ublock installed on, maybe there's a conflict ?

**Comment by TomerAberbach** [comment]
Can you try again and check your console logs for errors? And paste them here if there are any?

https://balsamiq.com/support/faqs/browserconsole

**Comment by Number-313** [comment]
```
TopSitesFeed: Failed to fetch data from Contile server: NetworkError when attempting to fetch resource. [TopSitesFeed.sys.mjs:542](resource://activity-stream/lib/TopSitesFeed.sys.mjs)
Failed to fetch https://spocs.getpocket.com/spocs: NetworkError when attempting to fetch resource. [DiscoveryStreamFeed.sys.mjs:400:15](resource://activity-stream/lib/DiscoveryStreamFeed.sys.mjs)
No response for spocs_endpoint prop [DiscoveryStreamFeed.sys.mjs:1101:19](resource://activity-stream/lib/DiscoveryStreamFeed.sys.mjs)
TypeError: NetworkError: Network request failed
    onerror resource://services-settings/Utils.sys.mjs:236
[IgnoreLists.sys.mjs:87:15](resource://gre/modules/IgnoreLists.sys.mjs)
Experiment add-an-image-to-pdf-with-alt-text-rollout has unknown featureId: addAnImageInPDF [RemoteSettingsExperimentLoader.sys.mjs:709:21](resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs)
Failed to fetch https://firefox-api-proxy.cdn.mozilla.net/desktop/v1/recommendations?locale=fr&region=FR&count=30: NetworkError when attempting to fetch resource. [DiscoveryStreamFeed.sys.mjs:400:15](resource://activity-stream/lib/DiscoveryStreamFeed.sys.mjs)
No response for feed [DiscoveryStreamFeed.sys.mjs:1446:17](resource://activity-stream/lib/DiscoveryStreamFeed.sys.mjs)
TypeError: NetworkError when attempting to fetch resource. [ASRouter.sys.mjs:119:13](resource:///modules/asrouter/ASRouter.sys.mjs)
ASRouter: CheckBrowserNeedsUpdate failed :>>  
XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "https://aus5.mozilla.org/update/6/Firefox/129.0/20240801122119/WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%252010.0.0.0.22631.3880%2520(x64)/ISET%3ASSE4_2%2CMEM%3A16263/default/default/update.xml?force=1", status: 0, statusText: "", responseType: "", response: "", responseText: "" }
[ASRouterTargeting.sys.mjs:263](resource:///modules/asrouter/ASRouterTargeting.sys.mjs)
Experiment add-an-image-to-pdf-with-alt-text-rollout has unknown featureId: addAnImageInPDF [RemoteSettingsExperimentLoader.sys.mjs:709:21](resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs)
Sync encountered an error - see about:sync-log for the log file. [policies.sys.mjs:972:15](resource://services-sync/policies.sys.mjs)
BroadcastService: receivedBroadcastMessage: handler for remote-settings/monitor_changes threw error: Error: Polling for changes failed: NetworkError: Network request failed.
    pollChanges resource://services-settings/remote-settings.sys.mjs:324
[PushBroadcastService.sys.mjs:258](resource://gre/modules/PushBroadcastService.sys.mjs)
Error: Polling for changes failed: NetworkError: Network request failed.
    pollChanges resource://services-settings/remote-settings.sys.mjs:324
[RemoteSettingsComponents.sys.mjs:20:15](resource://services-settings/RemoteSettingsComponents.sys.mjs)
this.window.gBrowserInit is undefined [ext-browser.js:1136:9](chrome://browser/content/parent/ext-browser.js)
Missing resource in locale fr: devtools/client/toolbox.ftl
```

**Comment by TomerAberbach** [comment]
None of those errors seem related to my website...

Is it correct that you're using Firefox? And you copied the logs from this thing?

![Screenshot 2024-08-15 at 8 47 32 PM](https://github.com/user-attachments/assets/a5ab0ba9-df7f-4160-8ae4-b8abdf161bdb)

**Comment by Number-313** [comment]
sorry, I'm an idiot, here's the actual log :  
`Uncaught (in promise) Error: Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately, re-authenticating the user won't help here. Body: {
  "error" : {
    "status" : 403,
    "message" : "Player command failed: Premium required",
    "reason" : "PREMIUM_REQUIRED"
  }
}
    validateResponse https://spotify-true-random.tomeraberba.ch/assets/route-B1Zx6w2Z.js:1`

**Comment by TomerAberbach** [comment]
I could probably display a better error message in the UI for this case, but that error message says it all. You need a Premium Spotify account to use an application that uses the Spotify API. I guess you're using a non-Premium account?

**Comment by Number-313** [comment]
Yes I don't have a premium account. But I've tried using an other project which works fine, so I believe it's possible to use the API without premium ? In any case, I believe we found the cause of the problem

the project I'm using : https://github.com/kartikk221/spotify-true-shuffle

**Comment by TomerAberbach** [comment]
Not sure. It's possible they're using the API in a different way, but I'm using this endpoint, which requires Premium

https://developer.spotify.com/documentation/web-api/reference/start-a-users-playback

**Comment by Number-313** [comment]
I understand. They're using it to create a playlist while I believe your app can play directly. Thanks for the quick replies !

**Comment by TomerAberbach** [comment]
No problem
